/**
 * Authoritative product catalog — backend source of truth.
 * Covers every product shown on the website (productsData.js models + applicationsData.js relatedProducts).
 * Frontend sends product names; this catalog enriches them with category, tier, and specs.
 */

const catalog = [

  // ── PCR — Thermal Cyclers ─────────────────────────────────────────────────
  {
    name: 'PowerFlex 96-Well System',
    categoryId: 'pcr', categoryTitle: 'PCR — Thermal Cyclers', familyName: 'PowerFlex Thermal Cycler', tier: 'Premium',
    tagline: 'Flexible blocks, fast ramp rates, intuitive touchscreen',
    keyFeatures: ['VeriFlex 6-zone gradient', 'Interchangeable block modules', '7-inch colour touchscreen', 'Up to 5 °C/s ramp rate'],
    keySpecs: { 'Block Format': '96-well (0.2 mL)', 'Ramp Rate': 'Up to 5 °C/s', 'Uniformity': '±0.2 °C' },
  },
  {
    name: 'PowerFlex 384-Well System',
    categoryId: 'pcr', categoryTitle: 'PCR — Thermal Cyclers', familyName: 'PowerFlex Thermal Cycler', tier: 'Advanced',
    tagline: 'High-throughput 384-well PCR with gradient optimisation',
    keyFeatures: ['High-throughput 384-well block', 'Gradient optimisation', 'Cloud connectivity option', 'Energy-saving idle mode'],
    keySpecs: { 'Block Format': '384-well', 'Ramp Rate': 'Up to 4 °C/s', 'Uniformity': '±0.3 °C' },
  },
  {
    name: 'MiniAmp Plus Thermal Cycler',
    categoryId: 'pcr', categoryTitle: 'PCR — Thermal Cyclers', familyName: 'MiniAmp Plus Thermal Cycler', tier: 'Standard',
    tagline: 'Compact, reliable end-point PCR for every lab',
    keyFeatures: ['Compact lightweight design', '96-well 0.2 mL block', 'VeriFlex technology', 'Energy-efficient operation'],
    keySpecs: { 'Block Format': '96-well (0.2 mL)', 'Ramp Rate': 'Up to 3 °C/s', 'Weight': '<5 kg' },
  },

  // ── Real-Time PCR Systems ─────────────────────────────────────────────────
  {
    name: 'QuantStudio 3 System',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'QuantStudio Real-Time PCR Systems', tier: 'Standard',
    tagline: 'Affordable entry-level qPCR with 4-colour multiplexing',
    keyFeatures: ['4-colour multiplexing', 'Touchscreen interface', '<40 min fast cycling', 'Compact footprint'],
    keySpecs: { 'Well Format': '96-well', 'Channels': '4 filter sets', 'Run Time': '<40 min (fast)' },
  },
  {
    name: 'QuantStudio 5 System',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'QuantStudio Real-Time PCR Systems', tier: 'Advanced',
    tagline: '5-colour multiplexing with cloud connectivity',
    keyFeatures: ['5-colour multiplexing', 'Cloud-based data analysis', 'TaqMan Array support', 'Remote run monitoring'],
    keySpecs: { 'Well Format': '96-well', 'Channels': '5 filter sets', 'Uniformity': '±0.2 °C', 'Connectivity': 'Cloud Connect' },
  },
  {
    name: 'QuantStudio 6 Flex System',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'QuantStudio Real-Time PCR Systems', tier: 'Premium',
    tagline: 'Interchangeable blocks with 6-dye multiplexing and HRM',
    keyFeatures: ['Interchangeable block system', '6-dye multiplexing', 'HRM genotyping', 'TaqMan Array Card support'],
    keySpecs: { 'Well Formats': '96-well, 384-well, Array Cards', 'Channels': '6 filter sets', 'HRM': 'High-resolution melt' },
  },
  {
    name: 'QuantStudio 7 Flex System',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'QuantStudio Real-Time PCR Systems', tier: 'Premium',
    tagline: 'High-throughput 384-well with robotic loading',
    keyFeatures: ['High-throughput 384-well', '±0.1 °C industry-leading uniformity', 'OpenArray compatibility', 'LIMS integration'],
    keySpecs: { 'Well Format': '384-well', 'Channels': '6 filter sets', 'Throughput': '4 × 384-well plates/day', 'Uniformity': '±0.1 °C' },
  },
  // Application-page names for real-time PCR
  {
    name: 'Real-Time PCR System (96-well)',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'QuantStudio Real-Time PCR Systems', tier: 'Standard',
    tagline: 'High-sensitivity 96-well quantitative PCR system',
    keyFeatures: ['96-well format', 'Multiplex detection', 'Validated assay kits', 'Fast 45-minute run time'],
    keySpecs: { 'Well Format': '96-well', 'Run Time': '<45 min' },
  },
  {
    name: 'Multiplex qPCR Master Mix',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'PCR Reagents & Consumables', tier: 'Standard',
    tagline: 'Optimised master mix for multiplex qPCR detection',
    keyFeatures: ['Multiplex-compatible formulation', 'Hot-start enzyme', 'ROX passive reference included', 'Broad instrument compatibility'],
    keySpecs: { 'Format': '2X concentrate', 'Multiplexing': 'Up to 4-plex', 'Volume': '1 mL, 5 mL' },
  },
  {
    name: 'Pathogen Detection Kit Panel',
    categoryId: 'realtime-pcr', categoryTitle: 'Real-Time PCR Systems', familyName: 'PCR Reagents & Consumables', tier: 'Standard',
    tagline: 'Ready-to-use panel for common pathogen detection by qPCR',
    keyFeatures: ['Multi-pathogen panel format', 'Pre-validated assays', 'Positive and negative controls included', 'CE-IVD marked (select panels)'],
    keySpecs: { 'Detection Method': 'Real-time PCR', 'Pathogens': 'Respiratory, GI, STI panels' },
  },

  // ── Next-Generation Sequencing ────────────────────────────────────────────
  {
    name: 'Genexus Integrated Sequencer',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'Genexus Integrated Sequencer', tier: 'Premium',
    tagline: 'Sample to results in a single day — fully automated',
    keyFeatures: ['Fully automated sample-to-report', 'Oncomine assay panel library', 'Same-day NGS results', 'Liquid biopsy compatible'],
    keySpecs: { 'Automation': 'Full (library prep → analysis)', 'Turnaround': '<24 hours', 'Sample Types': 'FFPE, blood, liquid biopsy' },
  },
  {
    name: 'Ion GeneStudio S5 System',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'Ion GeneStudio S5 System', tier: 'Standard',
    tagline: 'Scalable semiconductor sequencing for targeted panels',
    keyFeatures: ['Affordable targeted sequencing', 'Fast 2–4 hour run', 'Simple touchscreen interface', 'Small footprint'],
    keySpecs: { 'Chips': 'Ion 510, 520, 530', 'Output': 'Up to 15 Gb', 'Run Time': '2–4 hours' },
  },
  {
    name: 'Ion GeneStudio S5 Prime',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'Ion GeneStudio S5 System', tier: 'Premium',
    tagline: 'Exome-scale sequencing with up to 50 Gb output',
    keyFeatures: ['Exome-scale sequencing', 'High-output 550 chip (50 Gb)', 'Oncomine panel compatible', 'Pharmacogenomics applications'],
    keySpecs: { 'Chips': 'Ion 540, 550 (+ all lower)', 'Output': 'Up to 50 Gb', 'Read Length': 'Up to 600 bp' },
  },
  // Application-page names for NGS
  {
    name: 'Benchtop NGS Sequencer',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'Ion GeneStudio S5 System', tier: 'Standard',
    tagline: 'Compact benchtop NGS platform for targeted sequencing',
    keyFeatures: ['Short-read and long-read platforms', 'Automated library preparation', 'On-board bioinformatics pipeline', 'Clinical-grade variant calling'],
    keySpecs: { 'Platform': 'Semiconductor sequencing', 'Run Time': '2–4 hours' },
  },
  {
    name: 'Library Prep Automation Kit',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'NGS Reagents & Kits', tier: 'Advanced',
    tagline: 'Automated NGS library preparation kit',
    keyFeatures: ['Automated liquid-handling compatible', 'Low-input sample support', 'Unique dual indexing', 'Size selection included'],
    keySpecs: { 'Input': '1 ng – 1 µg DNA/RNA', 'Automation': 'Compatible with robotic handlers' },
  },
  {
    name: 'Variant Analysis Software',
    categoryId: 'ngs', categoryTitle: 'Next-Generation Sequencing', familyName: 'NGS Software', tier: 'Advanced',
    tagline: 'Clinical-grade variant analysis and annotation platform',
    keyFeatures: ['Clinical-grade variant calling', 'Annotation against ClinVar, COSMIC', 'Tumour mutational burden analysis', 'Regulatory-submission reporting'],
    keySpecs: { 'Platform': 'Cloud and on-premise', 'Compliance': '21 CFR Part 11 ready' },
  },

  // ── Nucleic Acid Extraction (application-page products) ───────────────────
  {
    name: 'Automated Nucleic Acid Extractor',
    categoryId: 'molecular-diagnostics', categoryTitle: 'Molecular Diagnostics', familyName: 'Nucleic Acid Extraction', tier: 'Advanced',
    tagline: 'Automated 96-sample extraction with integrated inhibitor removal',
    keyFeatures: ['Automated 96-sample processing', 'High-purity A260/280 > 1.8', 'Blood, tissue, swab compatibility', 'Integrated inhibitor removal'],
    keySpecs: { 'Throughput': '96 samples/run', 'Method': 'Magnetic bead-based' },
  },
  {
    name: 'RNA Extraction Spin Kit',
    categoryId: 'molecular-diagnostics', categoryTitle: 'Molecular Diagnostics', familyName: 'Nucleic Acid Extraction', tier: 'Standard',
    tagline: 'Spin-column RNA extraction with high-purity yield',
    keyFeatures: ['Column-based purification', 'DNase digestion included', 'Compatible with diverse sample types', 'RNase-free reagents'],
    keySpecs: { 'Yield': 'Up to 50 µg RNA', 'Format': '50 reactions/kit' },
  },
  {
    name: 'Viral RNA Isolation Kit',
    categoryId: 'molecular-diagnostics', categoryTitle: 'Molecular Diagnostics', familyName: 'Nucleic Acid Extraction', tier: 'Standard',
    tagline: 'Optimised viral RNA isolation from serum, plasma, and swabs',
    keyFeatures: ['Optimised for viral RNA recovery', 'Carrier RNA enhancement', 'Suitable for serum, plasma, swabs', 'Fast 30-minute protocol'],
    keySpecs: { 'Sample Volume': '140–200 µL', 'Elution Volume': '40–60 µL' },
  },

  // ── Sanger Sequencing (application-page products) ─────────────────────────
  {
    name: 'Capillary Electrophoresis System',
    categoryId: 'genetic-analyzer', categoryTitle: 'Genetic Analyzers', familyName: 'SeqStudio Flex Series', tier: 'Advanced',
    tagline: 'Capillary electrophoresis for Sanger sequencing and fragment analysis',
    keyFeatures: ['1–24 capillary configurations', 'Bidirectional sequencing support', 'Fragment analysis capability', 'PhiX-calibrated accuracy'],
    keySpecs: { 'Applications': 'Sanger sequencing, fragment analysis', 'Capillaries': '1–24' },
  },
  {
    name: 'BigDye Terminator Kit',
    categoryId: 'genetic-analyzer', categoryTitle: 'Genetic Analyzers', familyName: 'Sanger Sequencing Reagents', tier: 'Standard',
    tagline: 'Gold-standard BigDye Terminator Sanger sequencing chemistry',
    keyFeatures: ['BigDye Terminator v3.1 chemistry', 'Uniform peak height across all bases', 'Ready-to-use formulation', 'Compatible with all capillary analyzers'],
    keySpecs: { 'Read Length': 'Up to 1000 bp', 'Format': '100–400 reactions/kit' },
  },
  {
    name: 'Fragment Analysis Reagents',
    categoryId: 'genetic-analyzer', categoryTitle: 'Genetic Analyzers', familyName: 'Sanger Sequencing Reagents', tier: 'Standard',
    tagline: 'Polymer, formamide, and size standards for fragment analysis',
    keyFeatures: ['POP-4 and POP-7 polymer options', 'Hi-Di formamide', 'ROX size standards', 'Optimised for microsatellite analysis'],
    keySpecs: { 'Applications': 'STR genotyping, microsatellite analysis, LOH' },
  },

  // ── Genetic Analyzers (product-page models) ───────────────────────────────
  {
    name: 'SeqStudio Flex 8-Capillary',
    categoryId: 'genetic-analyzer', categoryTitle: 'Genetic Analyzers', familyName: 'SeqStudio Flex Series', tier: 'Premium',
    tagline: 'Higher-throughput HID and Sanger with 8 capillaries',
    keyFeatures: ['8-capillary throughput', 'Walk-up operation', 'RFID cartridge tracking', 'LIMS integration ready'],
    keySpecs: { 'Capillaries': '8', 'Applications': 'Sanger, fragment analysis, HID', 'Plate Format': '96-well' },
  },
  {
    name: 'SeqStudio Flex 4-Capillary',
    categoryId: 'genetic-analyzer', categoryTitle: 'Genetic Analyzers', familyName: 'SeqStudio Flex Series', tier: 'Standard',
    tagline: 'Cost-effective Sanger and HID with cartridge-free setup',
    keyFeatures: ['Cost-effective 4-capillary', 'Cartridge-based reagents', 'Ideal for low-volume labs', 'Upgrade path to 8-capillary'],
    keySpecs: { 'Capillaries': '4', 'Applications': 'Sanger, fragment analysis, HID', 'Plate Format': '96-well' },
  },

  // ── Cell Biology (application-page products) ──────────────────────────────
  {
    name: 'CO2 Incubator (170L)',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Culture & Expansion', tier: 'Advanced',
    tagline: '170 L CO2 incubator with precision humidity and gas control',
    keyFeatures: ['Precision CO2 and humidity control', 'HEPA-filtered airflow', 'Contamination-resistant interior', 'Data logging and alarms'],
    keySpecs: { 'Capacity': '170 L', 'CO2 Range': '0–20%', 'Temp Range': '5–50 °C' },
  },
  {
    name: 'Serum-Free Cell Culture Media',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Culture & Expansion', tier: 'Standard',
    tagline: 'Animal-free defined serum-free media for consistent cell growth',
    keyFeatures: ['Animal-free defined formulation', 'Lot-to-lot consistency', 'Broad cell-type compatibility', 'Cryopreservation compatible'],
    keySpecs: { 'Format': '500 mL, 1 L', 'Serum-free': 'Yes (animal-free)' },
  },
  {
    name: 'Class II Biosafety Cabinet',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Culture & Expansion', tier: 'Advanced',
    tagline: 'Class II Type A2 biosafety cabinet for cell culture and BSL-2 work',
    keyFeatures: ['Class II Type A2 protection', 'HEPA filtered supply and exhaust', 'Low-noise DC motor', 'NSF 49 / EN 12469 certified'],
    keySpecs: { 'Class': 'Class II Type A2', 'Widths': '900 mm, 1200 mm, 1500 mm', 'HEPA': '99.99% efficiency' },
  },
  {
    name: 'High-Parameter Flow Cytometer',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Flow Cytometry', tier: 'Premium',
    tagline: 'Up to 40-parameter flow cytometer for deep immunophenotyping',
    keyFeatures: ['Up to 40-parameter detection', 'Spectral unmixing algorithms', 'High-speed acquisition', 'Validated antibody panels'],
    keySpecs: { 'Parameters': 'Up to 40', 'Lasers': 'Up to 5', 'Events/sec': '>50,000' },
  },
  {
    name: 'Cell Sorter System',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Flow Cytometry', tier: 'Premium',
    tagline: 'High-speed fluorescence-activated cell sorter (FACS)',
    keyFeatures: ['High-speed cell sorting (>50,000 events/sec)', 'Multi-way sorting capability', 'Aerosol containment option', 'Index sorting for single cells'],
    keySpecs: { 'Sort Speed': '>50,000 events/sec', 'Sort Purity': '>98%', 'Sort Modes': '2-way, 4-way' },
  },
  {
    name: 'Lyophilized Antibody Panel Kit',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Flow Cytometry', tier: 'Advanced',
    tagline: 'Pre-validated lyophilised antibody panels for flow cytometry',
    keyFeatures: ['Pre-titrated antibody combinations', 'Lyophilized for stability', 'Minimal prep — just add cells', 'Validated for human and mouse'],
    keySpecs: { 'Format': 'Lyophilized tube', 'Panel Types': 'T-cell, B-cell, NK, myeloid panels' },
  },
  {
    name: 'Inverted Fluorescence Microscope',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Imaging & Analysis', tier: 'Advanced',
    tagline: 'Inverted fluorescence microscope for live-cell imaging',
    keyFeatures: ['Wide-field fluorescence', 'Phase contrast and DIC', 'Motorised stage option', 'Live-cell time-lapse imaging'],
    keySpecs: { 'Objectives': '4×–100×', 'Fluorescence Channels': '4+', 'Camera': 'Scientific CMOS' },
  },
  {
    name: 'High-Content Imaging System',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Imaging & Analysis', tier: 'Premium',
    tagline: 'Automated high-content imaging for plate-based cell assays',
    keyFeatures: ['Automated plate imaging', 'AI-driven image segmentation', 'Multi-channel fluorescence', 'High-throughput 96/384-well'],
    keySpecs: { 'Format': '96/384-well plate', 'Channels': 'Up to 5 fluorescence', 'Automation': 'Fully automated plate handling' },
  },
  {
    name: 'CellProfiler Analysis Software',
    categoryId: 'cell-biology', categoryTitle: 'Cell Biology', familyName: 'Cell Imaging & Analysis', tier: 'Standard',
    tagline: 'Open-source automated image analysis for cell biology',
    keyFeatures: ['Automated cell segmentation', 'Multi-channel image analysis', 'Batch processing pipeline', 'Machine learning classifiers'],
    keySpecs: { 'Platform': 'Windows, macOS, Linux', 'License': 'Open source (BSD)' },
  },

  // ── Cell & Gene Therapy (application-page products) ───────────────────────
  {
    name: 'Single-Use Bioreactor (3L–50L)',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Viral Vector Production', tier: 'Premium',
    tagline: 'Scalable single-use bioreactor for viral vector manufacturing',
    keyFeatures: ['Single-use vessel — no CIP/SIP', 'Scalable 3 L to 50 L', 'Integrated sensors (pH, DO, temp)', 'GMP-compatible design'],
    keySpecs: { 'Volumes': '3 L, 10 L, 30 L, 50 L', 'Agitation': 'Rocking or stirred-tank', 'Compliance': 'GMP-compatible' },
  },
  {
    name: 'Transfection Reagent Kit',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Viral Vector Production', tier: 'Advanced',
    tagline: 'High-efficiency transfection reagent for viral vector production',
    keyFeatures: ['High-efficiency transfection', 'Low cytotoxicity', 'Serum-compatible formulation', 'Scalable protocol'],
    keySpecs: { 'Cell Types': 'HEK293T, Sf9, adherent and suspension', 'Format': '1 mL, 5 mL, 25 mL' },
  },
  {
    name: 'AAV Purification Column',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Viral Vector Production', tier: 'Advanced',
    tagline: 'Affinity chromatography column for AAV serotype purification',
    keyFeatures: ['Serotype-specific affinity resin', 'High binding capacity', 'Scalable lab to GMP scale', 'Ready-to-use pre-packed'],
    keySpecs: { 'Serotypes': 'AAV2, AAV5, AAV8, AAV9', 'Format': '1 mL, 5 mL, 20 mL columns' },
  },
  {
    name: 'CRISPR-Cas9 Editing Kit',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Gene Editing (CRISPR)', tier: 'Advanced',
    tagline: 'Complete CRISPR-Cas9 editing toolkit for gene knockout and correction',
    keyFeatures: ['Pre-designed sgRNA libraries', 'Cas9 protein and mRNA options', 'HDR and NHEJ-optimised protocols', 'Off-target analysis support'],
    keySpecs: { 'Delivery': 'RNP, plasmid, or mRNA', 'Cell Types': 'Primary cells and cell lines' },
  },
  {
    name: 'Electroporation System',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Gene Editing (CRISPR)', tier: 'Advanced',
    tagline: 'Nucleofection-based electroporation for primary cell transfection',
    keyFeatures: ['High transfection efficiency', 'Low cell death protocol', 'Pre-optimised programs', 'Compatible with primary T-cells, NK cells'],
    keySpecs: { 'Cell Types': 'Primary cells, stem cells, neurons', 'Scale': '20 µL – 2 mL cuvettes' },
  },
  {
    name: 'Guide RNA Synthesis Kit',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Gene Editing (CRISPR)', tier: 'Standard',
    tagline: 'In vitro transcription kit for custom sgRNA synthesis',
    keyFeatures: ['T7 RNA polymerase-based synthesis', 'Chemical modification support', 'Purification column included', 'High yield per reaction'],
    keySpecs: { 'Yield': 'Up to 30 µg per reaction', 'sgRNA Length': '20 nt spacer + scaffold' },
  },
  {
    name: 'G-Rex Cell Expansion System',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Cell Therapy Manufacturing', tier: 'Advanced',
    tagline: 'Gas-permeable cell expansion vessel for T-cell and NK-cell therapy',
    keyFeatures: ['High-density T-cell expansion', 'Gas-permeable membrane', 'Minimal media changes required', 'Scalable from G-Rex 6 to G-Rex 100M'],
    keySpecs: { 'Formats': 'G-Rex 6, 10, 24, 100, 100M', 'Material': 'Gas-permeable polystyrene' },
  },
  {
    name: 'CAR-T Activation Kit',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Cell Therapy Manufacturing', tier: 'Premium',
    tagline: 'GMP-grade T-cell activation beads for CAR-T manufacturing',
    keyFeatures: ['Anti-CD3/CD28 activation', 'GMP-grade reagents', 'Consistent expansion fold', 'Bead removal step included'],
    keySpecs: { 'Activation': 'Anti-CD3/CD28 dynabeads', 'Scale': 'Research to GMP', 'Bead:Cell Ratio': '1:1–3:1' },
  },
  {
    name: 'Controlled-Rate Cell Freezer',
    categoryId: 'cell-gene-therapy', categoryTitle: 'Cell and Gene Therapy', familyName: 'Cell Therapy Manufacturing', tier: 'Advanced',
    tagline: 'Programmable controlled-rate freezer for cell therapy cryopreservation',
    keyFeatures: ['Programmable cooling rate (−0.1 to −10 °C/min)', 'Nucleation detection', 'GMP audit-trail data logging', 'Compatible with bags and vials'],
    keySpecs: { 'Cooling Rate': '0.1–10 °C/min', 'Capacity': 'Up to 96 vials or cryobags', 'Compliance': 'GMP / 21 CFR Part 11' },
  },

  // ── Analytical Science (application-page products) ────────────────────────
  {
    name: 'UHPLC System with DAD',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Chromatography (HPLC/UHPLC)', tier: 'Premium',
    tagline: 'Ultra-high-performance LC system with diode array detector',
    keyFeatures: ['Sub-2-micron column compatibility', 'DAD with 1.7 nm slit width', 'CFR Part 11 compliant software', 'Quaternary gradient system'],
    keySpecs: { 'Pressure': 'Up to 1500 bar', 'Detector': 'Diode Array Detector (DAD)', 'Compliance': '21 CFR Part 11' },
  },
  {
    name: 'Reversed-Phase C18 Columns',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Chromatography (HPLC/UHPLC)', tier: 'Standard',
    tagline: 'Reversed-phase C18 columns for pharmaceutical and food analysis',
    keyFeatures: ['C18 bonded silica', 'Wide pH stability', 'USP L1 classification', 'Available in multiple dimensions'],
    keySpecs: { 'Phase': 'C18 reversed phase', 'Particle Sizes': '1.8, 2.6, 3.5, 5 µm', 'pH Range': '1.5–10' },
  },
  {
    name: 'Chromatography Data System (CDS)',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Chromatography (HPLC/UHPLC)', tier: 'Premium',
    tagline: 'Multi-vendor chromatography data management and compliance system',
    keyFeatures: ['Multi-vendor LC/GC/IC support', '21 CFR Part 11 / EU Annex 11', 'Automated data review workflows', 'LIMS integration'],
    keySpecs: { 'Compliance': '21 CFR Part 11, EU Annex 11', 'Deployment': 'Workstation, Client-Server, Cloud' },
  },
  {
    name: 'LC-MS/MS Triple Quadrupole',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Mass Spectrometry', tier: 'Premium',
    tagline: 'Triple-quadrupole LC-MS/MS for targeted quantitation',
    keyFeatures: ['Triple-quadrupole MRM workflows', 'High sensitivity (low fg/mL)', 'Automated sample preparation', 'Regulatory-ready quantitation'],
    keySpecs: { 'Analyzer': 'Triple quadrupole (QqQ)', 'Mode': 'MRM / SRM', 'Mass Range': '5–2000 m/z' },
  },
  {
    name: 'QTOF High-Resolution System',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Mass Spectrometry', tier: 'Premium',
    tagline: 'Quadrupole-TOF high-resolution accurate mass spectrometer',
    keyFeatures: ['High-resolution accurate mass (HRMS)', '<2 ppm mass accuracy', 'MS/MS spectral library matching', 'Untargeted metabolomics'],
    keySpecs: { 'Analyzer': 'Quadrupole-TOF (QTOF)', 'Resolution': '>40,000 FWHM', 'Mass Accuracy': '<2 ppm' },
  },
  {
    name: 'Automated SPE Station',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Mass Spectrometry', tier: 'Advanced',
    tagline: 'Automated solid-phase extraction workstation for sample prep',
    keyFeatures: ['Automated 96-well SPE', 'Compatible with mixed-mode sorbents', 'Vacuum manifold controlled', 'Protocol storage and recall'],
    keySpecs: { 'Format': '96-well and cartridge', 'Volume Range': '0.1–10 mL', 'Throughput': '96 samples/run' },
  },
  {
    name: 'UV-Vis Spectrophotometer',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Spectroscopy (UV/Vis & IR)', tier: 'Standard',
    tagline: 'Double-beam UV-Vis spectrophotometer for purity and concentration',
    keyFeatures: ['Single and double-beam configurations', 'Wavelength range 190–1100 nm', 'GMP-ready software module', 'FDA 21 CFR Part 11 compliance'],
    keySpecs: { 'Wavelength Range': '190–1100 nm', 'Bandwidth': '1 nm', 'Light Sources': 'D2 + Tungsten' },
  },
  {
    name: 'ATR-FTIR Spectrometer',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Spectroscopy (UV/Vis & IR)', tier: 'Advanced',
    tagline: 'ATR-FTIR spectrometer for material identification and QC',
    keyFeatures: ['ATR-FTIR accessory included', 'Spectral library matching', 'Identity testing and polymorphism', 'GMP-compliant software'],
    keySpecs: { 'Resolution': '0.5–64 cm⁻¹', 'Wavenumber Range': '4000–400 cm⁻¹', 'Detector': 'DTGS / MCT' },
  },
  {
    name: 'Handheld Raman Analyzer',
    categoryId: 'analytical-science', categoryTitle: 'Analytical Science', familyName: 'Spectroscopy (UV/Vis & IR)', tier: 'Advanced',
    tagline: 'Portable handheld Raman for raw material ID and incoming QC',
    keyFeatures: ['Non-destructive through-container analysis', 'Spectral library of >10,000 compounds', 'GMP 21 CFR Part 11 mode', 'Battery-powered field use'],
    keySpecs: { 'Laser': '785 nm', 'Range': '200–3200 cm⁻¹', 'Weight': '<1.5 kg' },
  },

  // ── Chromatography (product-page models) ──────────────────────────────────
  {
    name: 'Vanquish UHPLC System',
    categoryId: 'chromatography', categoryTitle: 'Chromatography', familyName: 'HPLC & UHPLC Systems', tier: 'Premium',
    tagline: 'Up to 1500 bar — sub-2-minute separations',
    keyFeatures: ['Ternary gradient capability', 'Biocompatible or stainless path', 'Integrated column oven', 'MS-ready detector options'],
    keySpecs: { 'Pressure': 'Up to 1500 bar', 'Flow Range': '0.001–5 mL/min', 'Software': 'Chromeleon CDS' },
  },
  {
    name: 'UltiMate 3000 HPLC',
    categoryId: 'chromatography', categoryTitle: 'Chromatography', familyName: 'HPLC & UHPLC Systems', tier: 'Standard',
    tagline: 'Versatile analytical-to-semi-prep HPLC platform',
    keyFeatures: ['Modular architecture', 'Wide solvent compatibility', 'Automated column switching', '21 CFR Part 11 compliant'],
    keySpecs: { 'Pressure': 'Up to 620 bar', 'Flow Range': '0.001–10 mL/min', 'Scale': 'Analytical to semi-prep' },
  },
  {
    name: 'Accucore C18 Column',
    categoryId: 'chromatography', categoryTitle: 'Chromatography', familyName: 'Columns & Consumables', tier: 'Advanced',
    tagline: 'Core-shell C18 — sub-2-µm efficiency at lower pressure',
    keyFeatures: ['Sub-2-µm equivalent efficiency', 'Lower backpressure', 'Batch-to-batch consistency', 'USP L1 classification'],
    keySpecs: { 'Particle': '2.6 µm core-shell', 'Phase': 'C18 reversed phase', 'pH Range': '1.5–11' },
  },
  {
    name: 'Chromeleon 7 CDS',
    categoryId: 'chromatography', categoryTitle: 'Chromatography', familyName: 'Chromeleon CDS Software', tier: 'Premium',
    tagline: 'Unified multi-vendor chromatography data system',
    keyFeatures: ['Multi-vendor LC/GC/IC support', '21 CFR Part 11 / EU Annex 11', 'Role-based access control', 'LIMS / ERP connectable'],
    keySpecs: { 'Compliance': '21 CFR Part 11, EU Annex 11', 'Deployment': 'Workstation / Client-Server / Cloud' },
  },

  // ── Chemicals & Reagents (application-page products) ──────────────────────
  {
    name: 'Acetonitrile (LC-MS Grade, 4L)',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'HPLC & Analytical Grade Solvents', tier: 'Premium',
    tagline: 'LC-MS grade acetonitrile — ultra-low UV cutoff',
    keyFeatures: ['LC-MS grade purity', 'Ultra-low UV absorbance (<190 nm)', 'Certificate of Analysis per lot', '<0.2 µm filtered'],
    keySpecs: { 'Purity': '≥99.9% LC-MS grade', 'Pack Size': '4 L', 'UV Cutoff': '<190 nm' },
  },
  {
    name: 'Methanol (HPLC Grade)',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'HPLC & Analytical Grade Solvents', tier: 'Standard',
    tagline: 'HPLC grade methanol with low UV absorbance',
    keyFeatures: ['HPLC grade purity', 'Low residue after evaporation', 'Lot-to-lot consistency', 'Available in 1 L to 20 L'],
    keySpecs: { 'Purity': '≥99.9% HPLC grade', 'Pack Sizes': '1 L, 4 L, 20 L' },
  },
  {
    name: 'Water (LC-MS Grade)',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'HPLC & Analytical Grade Solvents', tier: 'Standard',
    tagline: 'LC-MS grade water for mobile phase and sample preparation',
    keyFeatures: ['Resistivity ≥18.2 MΩ·cm', 'TOC <5 ppb', '<0.2 µm filtered', 'Lot-specific CoA'],
    keySpecs: { 'Resistivity': '≥18.2 MΩ·cm', 'TOC': '<5 ppb', 'Pack Size': '1 L, 4 L' },
  },
  {
    name: 'Pharmacopoeial Reference Standards',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Reference Standards', tier: 'Premium',
    tagline: 'USP, EP, and BP certified reference standards',
    keyFeatures: ['USP, EP, and BP grade', 'Traceable to NIST/SI units', 'Certificate of Analysis included', 'Long shelf-life stable formulations'],
    keySpecs: { 'Grades': 'USP, EP, BP, ICH', 'Traceability': 'NIST / SI units' },
  },
  {
    name: 'Environmental Calibration Mix',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Reference Standards', tier: 'Standard',
    tagline: 'Multi-compound environmental calibration standard mixture',
    keyFeatures: ['Multi-compound certified mixture', 'GC and LC compatible', 'Traceable concentrations', 'Stable in DMSO or methanol'],
    keySpecs: { 'Matrix': 'Acetonitrile / methanol solution', 'Traceability': 'ISO 17034 certified' },
  },
  {
    name: 'Multi-element ICP Standard',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Reference Standards', tier: 'Standard',
    tagline: 'Multi-element ICP-OES/MS calibration standard',
    keyFeatures: ['Certified multi-element solution', 'Traceable to NIST SRM', 'Acidified matrix for stability', 'Covers 30+ elements'],
    keySpecs: { 'Elements': '>30 elements per mix', 'Concentration': '10 mg/L each', 'Matrix': '2–5% HNO3' },
  },
  {
    name: 'Agarose Gel (Molecular Grade)',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Biochemical Reagents', tier: 'Standard',
    tagline: 'Molecular grade agarose for DNA electrophoresis',
    keyFeatures: ['RNase/DNase-free certification', 'High gel strength', 'Sharp band resolution', 'Low EEO value'],
    keySpecs: { 'Grade': 'Molecular biology grade', 'EEO': '<0.09', 'Pack Sizes': '100 g, 500 g' },
  },
  {
    name: 'Protein Assay Kit (Bradford)',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Biochemical Reagents', tier: 'Standard',
    tagline: 'Colorimetric Bradford protein quantitation assay kit',
    keyFeatures: ['Bradford Coomassie-based method', 'BSA standard curve included', 'Microplate and cuvette formats', '5-minute room-temperature assay'],
    keySpecs: { 'Detection Range': '0.1–2 mg/mL (standard)', 'Format': '96-well microplate or cuvette' },
  },
  {
    name: 'Restriction Enzyme Set',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Biochemical Reagents', tier: 'Standard',
    tagline: 'Common restriction enzyme set for cloning and mapping',
    keyFeatures: ['Unit-activity and stability tested', 'Buffer-specific formulations', 'Heat-inactivatable options', 'Ready-to-use 10× buffers'],
    keySpecs: { 'Enzymes Included': 'EcoRI, BamHI, HindIII, NcoI, XbaI etc.', 'Activity': '10,000 U/mL' },
  },

  // ── Chemicals (product-page models) ───────────────────────────────────────
  {
    name: 'Optima LC-MS Grade Solvents',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'Analytical & HPLC-Grade Solvents', tier: 'Premium',
    tagline: 'Guaranteed purity for sensitive LC-MS workflows',
    keyFeatures: ['ACN, MeOH, water, IPA available', 'Nano-flow LC compatible', 'Formic acid and TFA buffers', 'Lot-specific CoA provided'],
    keySpecs: { 'Purity': '≥99.9% LC-MS grade', 'Residue': '<0.0001%', 'Pack Sizes': '1 L, 4 L, 20 L' },
  },
  {
    name: 'Fisher Chemical Range',
    categoryId: 'chemicals', categoryTitle: 'Chemicals & Reagents', familyName: 'General Laboratory Chemicals', tier: 'Standard',
    tagline: '>10,000 chemicals — ACS to technical grade',
    keyFeatures: ['Acids, bases, salts, buffers', 'ACS, reagent, purified, technical grades', 'Safety data sheets included', 'Bulk packaging available'],
    keySpecs: { 'Grades': 'ACS, reagent, purified, technical', 'Coverage': '>10,000 products', 'Packaging': '100 mL to 25 L' },
  },

  // ── Forensic Science (application-page products) ──────────────────────────
  {
    name: 'Forensic DNA Extraction Kit',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Human Identification (HID)', tier: 'Standard',
    tagline: 'Validated forensic DNA extraction from challenging evidence types',
    keyFeatures: ['CODIS-compatible protocols', 'Low-copy number support', 'Differential extraction capability', 'Chain-of-custody documentation'],
    keySpecs: { 'Sample Types': 'Blood, saliva, hair, semen, touch DNA', 'Format': '96-well or tube' },
  },
  {
    name: 'GlobalFiler STR Amplification Kit',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Human Identification (HID)', tier: 'Premium',
    tagline: 'CODIS-validated 24-locus STR kit for forensic human ID',
    keyFeatures: ['24 loci including Amelogenin', 'CODIS 20-core loci compliant', 'Mixture interpretation compatible', 'Validated for low template input'],
    keySpecs: { 'Loci': '24 (including Y-indel)', 'Input DNA': '0.5 ng recommended', 'CE Platform': 'SeqStudio / 3500 Series' },
  },
  {
    name: 'Genetic Analyzer (HID)',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Human Identification (HID)', tier: 'Premium',
    tagline: 'Capillary electrophoresis genetic analyzer optimised for forensic HID',
    keyFeatures: ['HID-validated CE platform', 'GlobalFiler and PowerPlex compatible', 'CODIS-ready data output', 'Chain-of-custody tracking'],
    keySpecs: { 'Capillaries': '4 or 8', 'Applications': 'STR profiling, HID, paternity testing' },
  },
  {
    name: 'DOA Immunoassay Analyzer',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Toxicology', tier: 'Advanced',
    tagline: 'Automated immunoassay analyzer for drugs-of-abuse screening',
    keyFeatures: ['Multi-drug immunoassay panels', 'Urine and oral fluid compatible', 'Rapid 5–10 min results', 'SOFT/AAFS-compliant protocols'],
    keySpecs: { 'Drug Classes': '10+ classes (opiates, amphetamines, cannabinoids, etc.)', 'Throughput': '>100 tests/hour' },
  },
  {
    name: 'Toxicology LC-MS/MS System',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Toxicology', tier: 'Premium',
    tagline: 'LC-MS/MS confirmation system for forensic toxicology',
    keyFeatures: ['LC-MS/MS confirmation libraries', 'Hair, blood, urine matrices', 'Automated sample preparation', 'Forensic-validated MRM methods'],
    keySpecs: { 'Analyzer': 'Triple quadrupole (QqQ)', 'Compounds': '>500 compound libraries' },
  },
  {
    name: 'Solid-Phase Extraction Plates',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Toxicology', tier: 'Standard',
    tagline: '96-well SPE plates for forensic toxicology sample clean-up',
    keyFeatures: ['Mixed-mode and reversed-phase sorbents', '96-well format', 'Compatible with vacuum manifold', 'High recovery for drugs and metabolites'],
    keySpecs: { 'Format': '96-well plate', 'Sorbent Mass': '5–30 mg per well', 'Volume': '1–3 mL' },
  },
  {
    name: 'Forensic FTIR Microscope',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Trace & Digital Evidence', tier: 'Premium',
    tagline: 'FTIR microscope for fibre, paint, and trace evidence analysis',
    keyFeatures: ['Micro-ATR and transmission modes', 'Spectral library >10,000 compounds', 'GSR and paint chip analysis', 'Mapping and imaging capability'],
    keySpecs: { 'Spatial Resolution': '<10 µm', 'Wavenumber Range': '4000–600 cm⁻¹', 'Detector': 'MCT (cooled)' },
  },
  {
    name: 'SEM-EDX System',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Trace & Digital Evidence', tier: 'Premium',
    tagline: 'Scanning electron microscope with EDX for forensic trace analysis',
    keyFeatures: ['Scanning electron microscopy (SEM-EDX)', 'GSR elemental mapping', 'High-resolution surface imaging', 'Automated particle search software'],
    keySpecs: { 'Resolution': '<4 nm SE', 'Accelerating Voltage': '0.5–30 kV', 'EDX': 'Silicon drift detector' },
  },
  {
    name: 'Digital Evidence Workstation',
    categoryId: 'forensic-science', categoryTitle: 'Forensic Science', familyName: 'Trace & Digital Evidence', tier: 'Advanced',
    tagline: 'Digital forensics workstation for cyber and device evidence analysis',
    keyFeatures: ['Digital evidence chain-of-custody', 'Write-blocked imaging capability', 'Multi-OS forensic analysis', 'Data recovery and carving tools'],
    keySpecs: { 'Function': 'Digital forensics analysis platform', 'OS Support': 'Windows, macOS, Linux, mobile' },
  },

  // ── Animal Health (application-page products) ─────────────────────────────
  {
    name: 'Canine/Feline Combo Rapid Test',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Rapid Diagnostics', tier: 'Standard',
    tagline: 'Rapid lateral flow test for common canine and feline diseases',
    keyFeatures: ['10–15 minute result', 'Species-validated kit', 'No refrigeration required', 'High sensitivity and specificity'],
    keySpecs: { 'Species': 'Canine, feline', 'Test Type': 'Antigen/antibody rapid lateral flow' },
  },
  {
    name: 'Avian Influenza Antigen Kit',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Rapid Diagnostics', tier: 'Standard',
    tagline: 'Rapid antigen detection kit for avian influenza (AI)',
    keyFeatures: ['OIE-validated method', 'Detects H5 and H7 subtypes', 'Cloacal and tracheal swab compatible', 'Result in 15 minutes'],
    keySpecs: { 'Target': 'Avian Influenza Nucleoprotein', 'Subtypes': 'H5, H7 and other subtypes', 'Result Time': '15 minutes' },
  },
  {
    name: 'Foot and Mouth Disease Test',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Rapid Diagnostics', tier: 'Advanced',
    tagline: 'Rapid or ELISA-based FMD antigen and antibody detection',
    keyFeatures: ['USDA/OIE validated', 'Serotype differentiation capability', 'Epithelium and serum compatible', 'Quantitative ELISA format available'],
    keySpecs: { 'Serotypes': 'O, A, C, SAT1, SAT2, SAT3, Asia1', 'Formats': 'Rapid test or ELISA plate' },
  },
  {
    name: 'Veterinary Haematology Analyzer',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Clinical Chemistry', tier: 'Advanced',
    tagline: 'Automated haematology analyzer with species-specific reference ranges',
    keyFeatures: ['Species-specific reference ranges', 'Whole-blood haematology profiles', '22-parameter CBC + differential', 'Small sample volume (<0.5 mL)'],
    keySpecs: { 'Parameters': '22 (CBC + 5-part differential)', 'Species': 'Canine, feline, equine, bovine', 'Sample': '0.2–0.5 mL EDTA blood' },
  },
  {
    name: 'Portable Biochemistry Analyzer',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Clinical Chemistry', tier: 'Standard',
    tagline: 'Compact portable biochemistry analyzer for in-clinic testing',
    keyFeatures: ['Comprehensive metabolic panel', 'Rotor-based dry chemistry', 'Results in 12 minutes', 'Battery-powered for field use'],
    keySpecs: { 'Analytes': 'Up to 25 chemistry parameters', 'Sample Volume': '100 µL whole blood or serum', 'Result Time': '<12 minutes' },
  },
  {
    name: 'Urine Dipstick Reader',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Veterinary Clinical Chemistry', tier: 'Standard',
    tagline: 'Automated dipstick reader for veterinary urinalysis',
    keyFeatures: ['Urine sediment analysis', 'Eliminates subjective reading', 'Multiple dipstick brand compatibility', 'Result storage and connectivity'],
    keySpecs: { 'Parameters': 'Up to 14 urine chemistry', 'Throughput': '~120 strips/hour' },
  },
  {
    name: 'Veterinary Real-Time PCR System',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Molecular Veterinary Diagnostics', tier: 'Advanced',
    tagline: 'Real-time PCR system with OIE-validated veterinary assays',
    keyFeatures: ['OIE-validated molecular assays', 'Multi-pathogen panel PCR kits', 'Fast 90-minute protocol', 'NABL-accreditable workflows'],
    keySpecs: { 'Well Format': '96-well', 'Channels': '4–6 fluorescence', 'Run Time': '<90 minutes' },
  },
  {
    name: 'Avian Serology ELISA Kit',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Molecular Veterinary Diagnostics', tier: 'Standard',
    tagline: 'Competitive ELISA for avian pathogen antibody titre testing',
    keyFeatures: ['ELISA antibody titre assays', 'OIE-validated serology', '96-well microplate format', 'Quantitative S/P ratio output'],
    keySpecs: { 'Target Pathogens': 'AI, ND, IBD, IBV, MG, MS', 'Format': '96-well ELISA', 'Result Time': '2–3 hours' },
  },
  {
    name: 'Multiplex Respiratory Panel',
    categoryId: 'animal-health', categoryTitle: 'Animal Health', familyName: 'Molecular Veterinary Diagnostics', tier: 'Advanced',
    tagline: 'Multiplex PCR panel for veterinary respiratory pathogens',
    keyFeatures: ['Multi-pathogen simultaneous detection', 'Bovine, porcine, and equine panels', 'Single-run result for 10+ pathogens', 'Ready-to-use lyophilised format'],
    keySpecs: { 'Pathogens/Panel': '10–15 targets', 'Species': 'Bovine, porcine, equine, canine', 'Format': '96-well PCR plate' },
  },

  // ── Agri, Veterinary & Animal Health (application-page products) ──────────
  {
    name: 'GC-MS/MS Triple Quadrupole',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Pesticide & Residue Testing', tier: 'Premium',
    tagline: 'GC-MS/MS for multi-residue pesticide analysis in food and feed',
    keyFeatures: ['QuEChERS-optimised workflows', '>500 compound screening panels', 'EU MRL-compliant reporting', 'Automated data processing'],
    keySpecs: { 'Analyzer': 'Triple quadrupole (QqQ)', 'Mode': 'MRM', 'Compounds': '>500 pesticide methods' },
  },
  {
    name: 'QuEChERS Extraction Kits',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Pesticide & Residue Testing', tier: 'Standard',
    tagline: 'QuEChERS dispersive SPE kits for pesticide sample preparation',
    keyFeatures: ['EN 15662 / AOAC 2007.01 compliant', 'Buffered and unbuffered versions', 'Dispersive-SPE clean-up included', 'For fruits, vegetables, cereals'],
    keySpecs: { 'Standards': 'EN 15662, AOAC 2007.01', 'Matrix': 'Fruits, vegetables, grains, feed' },
  },
  {
    name: 'Pesticide Reference Standard Mix',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Pesticide & Residue Testing', tier: 'Standard',
    tagline: 'Certified multi-residue pesticide calibration standard mixture',
    keyFeatures: ['Multi-residue certified mix', '>100 pesticides per solution', 'Traceable concentrations', 'Stable in acetonitrile'],
    keySpecs: { 'Compounds': '>100 pesticides', 'Concentration': '10 µg/mL each', 'Traceability': 'ISO 17034 certified' },
  },
  {
    name: 'ICP-OES Spectrometer',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Soil & Water Analysis', tier: 'Premium',
    tagline: 'ICP-OES for multi-element heavy metal analysis in soil and water',
    keyFeatures: ['Multi-element simultaneous analysis', 'Axial and radial dual view', 'ppb-level detection limits', 'Automated calibration and QC'],
    keySpecs: { 'Elements': 'Up to 70+ simultaneously', 'Detection Limit': 'Sub-ppb for most elements', 'View': 'Axial + Radial dual view' },
  },
  {
    name: 'Ion Chromatography System',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Soil & Water Analysis', tier: 'Advanced',
    tagline: 'Ion chromatography for anion and cation analysis in water and soil',
    keyFeatures: ['Suppressed conductivity detection', 'Simultaneous anion/cation analysis', 'Automated eluent generation', 'EPA and ISO method compliance'],
    keySpecs: { 'Analytes': 'Fluoride, chloride, nitrate, sulfate, phosphate, etc.', 'Detection': 'Suppressed conductivity / UV' },
  },
  {
    name: 'Portable Multiparameter Meter',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Soil & Water Analysis', tier: 'Standard',
    tagline: 'Portable meter for pH, EC, DO, turbidity, and temperature in the field',
    keyFeatures: ['Multi-parameter in single device', 'IP67 waterproof rating', 'GLP data logging', 'Bluetooth smartphone connectivity'],
    keySpecs: { 'Parameters': 'pH, EC, DO, ORP, turbidity, temp', 'Protection': 'IP67 waterproof', 'Battery': '400 hours typical' },
  },
  {
    name: 'Mycotoxin Rapid Test Reader',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Mycotoxin & Allergen Testing', tier: 'Advanced',
    tagline: 'Quantitative lateral flow reader for mycotoxin and allergen testing',
    keyFeatures: ['Lateral flow quantitative reader', 'ppb-level sensitivity', 'FSSAI and Codex compliant', 'Bluetooth data connectivity'],
    keySpecs: { 'Mycotoxins': 'Aflatoxin, Ochratoxin, DON, ZEN, T-2/HT-2, Fumonisins', 'Format': 'Lateral flow strip reader' },
  },
  {
    name: 'Aflatoxin ELISA Kit',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Mycotoxin & Allergen Testing', tier: 'Standard',
    tagline: 'Competitive ELISA kit for aflatoxin B1/total quantitation',
    keyFeatures: ['Competitive ELISA format', 'ppb-level quantitation', 'Validated in grain, feed, spices', 'Codex and EU limit compliant'],
    keySpecs: { 'Target': 'Aflatoxin B1 / Total Aflatoxins', 'Detection Limit': '<0.5 ppb', 'Format': '96-well plate' },
  },
  {
    name: 'Allergen Detection Panel',
    categoryId: 'agri-veterinary', categoryTitle: 'Agri, Veterinary & Animal Health', familyName: 'Mycotoxin & Allergen Testing', tier: 'Advanced',
    tagline: 'Multiplex allergen ELISA panel for major food allergens',
    keyFeatures: ['14 EU-regulated allergens panel', 'ELISA microplate format', 'Quantitative results in 90 min', 'FSSAI compliant testing'],
    keySpecs: { 'Allergens': 'Peanut, gluten, milk, egg, soy, tree nuts, etc.', 'Format': '96-well ELISA', 'Sensitivity': '<1–5 ppm' },
  },

  // ── Point of Care Solutions (application-page products) ───────────────────
  {
    name: 'Portable Molecular POC Reader',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Molecular POC Testing', tier: 'Advanced',
    tagline: 'CLIA-waived portable molecular reader for rapid infectious disease testing',
    keyFeatures: ['Results in under 30 minutes', 'CLIA-waived operation', 'Cartridge-based, no sample prep', 'Battery-powered for remote use'],
    keySpecs: { 'Technology': 'RT-LAMP or rapid PCR', 'Result Time': '<30 minutes', 'CLIA Status': 'Waived' },
  },
  {
    name: 'Respiratory Syndromic Panel',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Molecular POC Testing', tier: 'Advanced',
    tagline: 'Multiplex respiratory syndromic panel cartridge (Flu A/B, RSV, COVID-19)',
    keyFeatures: ['Flu A/B, RSV, COVID-19, para-influenza', 'Single cartridge workflow', 'Result in 15–30 minutes', 'NPS or nasal swab input'],
    keySpecs: { 'Targets': 'Flu A, Flu B, RSV, SARS-CoV-2, para-Influenza', 'Result Time': '15–30 minutes' },
  },
  {
    name: 'STI Cartridge Panel',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Molecular POC Testing', tier: 'Advanced',
    tagline: 'Rapid molecular STI panel for Chlamydia, Gonorrhoea, and Trichomonas',
    keyFeatures: ['CT/NG/TV simultaneous detection', 'Vaginal or urine samples', 'CLIA-waived result in 30 min', 'No laboratory required'],
    keySpecs: { 'Targets': 'CT, NG, TV (+ optional MG, HSV)', 'Result Time': '<30 minutes' },
  },
  {
    name: 'Quantitative Rapid Test Reader',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Immunoassay & Lateral Flow', tier: 'Advanced',
    tagline: 'Benchtop quantitative reader for immunoassay lateral flow strips',
    keyFeatures: ['Quantitative reader-based results', 'Bluetooth data connectivity', 'Multiple assay compatibility', 'QC management software'],
    keySpecs: { 'Format': 'Lateral flow strip reader', 'Result Time': '10–15 minutes', 'Connectivity': 'Bluetooth, USB, LIS' },
  },
  {
    name: 'Cardiac Panel Cartridge',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Immunoassay & Lateral Flow', tier: 'Premium',
    tagline: 'Point-of-care cardiac biomarker panel cartridge (troponin, BNP, D-dimer)',
    keyFeatures: ['Troponin I/T, BNP/NT-proBNP, D-dimer', 'Whole-blood capillary sample', '10-minute turnaround', 'Quantitative results'],
    keySpecs: { 'Biomarkers': 'Troponin I/T, BNP, NT-proBNP, D-dimer, CK-MB', 'Sample': 'Whole blood (100 µL)', 'Result Time': '<10 minutes' },
  },
  {
    name: 'CRP/PCT Rapid Test Kit',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Immunoassay & Lateral Flow', tier: 'Standard',
    tagline: 'Rapid quantitative CRP and procalcitonin (PCT) test kit',
    keyFeatures: ['CRP and PCT inflammation markers', 'Quantitative result', 'Finger-prick whole blood', 'Sepsis and infection triage'],
    keySpecs: { 'Markers': 'CRP (mg/L), PCT (ng/mL)', 'Sample': '10–20 µL whole blood', 'Result Time': '15 minutes' },
  },
  {
    name: 'Point-of-Care HbA1c Analyzer',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Blood Glucose & HbA1c', tier: 'Advanced',
    tagline: 'NGSP-certified HbA1c analyzer for diabetes management at POC',
    keyFeatures: ['NGSP-certified measurement', 'Fingerstick whole-blood sample', 'EMR/LIS connectivity', 'QC data management software'],
    keySpecs: { 'Method': 'NGSP-certified immunoassay or HPLC', 'Sample': '1.5–5 µL whole blood', 'Result Time': '<5 minutes' },
  },
  {
    name: 'Blood Glucose Monitor (Clinical)',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Blood Glucose & HbA1c', tier: 'Standard',
    tagline: 'Clinical blood glucose monitoring system for hospital POC use',
    keyFeatures: ['ISO 15197:2013 accuracy', 'Hematocrit correction', 'Connectivity to EMR/HIS', 'Control lockout and QC management'],
    keySpecs: { 'Range': '10–600 mg/dL', 'Sample Volume': '<1 µL', 'Result Time': '<5 seconds' },
  },
  {
    name: 'Blood Gas & Electrolyte Analyzer',
    categoryId: 'point-of-care', categoryTitle: 'Point of Care Solutions', familyName: 'Blood Glucose & HbA1c', tier: 'Premium',
    tagline: 'Critical care blood gas and electrolyte analyzer for ICU and ED use',
    keyFeatures: ['pH, pCO2, pO2, Na, K, Cl, Ca, Glucose, Lactate', 'Whole-blood single syringe input', 'Results in 60 seconds', 'Operator and patient ID lockout'],
    keySpecs: { 'Parameters': 'pH, pCO2, pO2, electrolytes, metabolites', 'Sample': '0.2–0.5 mL arterial blood', 'Result Time': '<60 seconds' },
  },

  // ── Lab Equipment (application-page products) ─────────────────────────────
  {
    name: 'Refrigerated Microcentrifuge',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Centrifugation', tier: 'Advanced',
    tagline: 'Refrigerated microcentrifuge for temperature-sensitive samples',
    keyFeatures: ['Refrigerated (−10 to +40 °C)', 'Up to 21,000 × g', 'Fixed-angle and strip-tube rotors', 'Quiet brushless motor'],
    keySpecs: { 'Max Speed': 'Up to 21,000 × g', 'Temperature': '−10 to +40 °C', 'Capacity': '24 × 1.5/2.0 mL' },
  },
  {
    name: 'Floor-Standing Ultracentrifuge',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Centrifugation', tier: 'Premium',
    tagline: 'Floor-standing ultracentrifuge up to 150,000 × g',
    keyFeatures: ['Up to 150,000 × g', 'Swinging-bucket and fixed-angle rotors', 'Density gradient separation', 'Imbalance detection and auto-stop'],
    keySpecs: { 'Max Speed': '150,000 × g', 'Temperature': '4–40 °C', 'Rotors': 'Ti, SW, and vertical rotors' },
  },
  {
    name: 'High-Capacity Centrifuge (6×1L)',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Centrifugation', tier: 'Advanced',
    tagline: 'High-capacity floor-standing centrifuge with 6 × 1 L rotor',
    keyFeatures: ['6 × 1 L swing-out rotor', 'Refrigerated operation', 'Pre-programmed blood bank protocols', 'Touchscreen interface'],
    keySpecs: { 'Capacity': '6 × 1000 mL', 'Max Speed': 'Up to 10,000 × g', 'Temperature': '−10 to +40 °C' },
  },
  {
    name: '-80°C ULT Freezer (500L)',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Cold Chain & Storage', tier: 'Premium',
    tagline: '−80 °C ultra-low temperature energy-efficient freezer (500 L)',
    keyFeatures: ['−80 °C energy-efficient models', 'IoT temperature alarm system', 'Cascade refrigeration system', 'USB temperature data download'],
    keySpecs: { 'Capacity': '500 L', 'Temperature': '−50 to −86 °C', 'Alarm': 'Audible, visual, remote' },
  },
  {
    name: 'Blood Bank Refrigerator',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Cold Chain & Storage', tier: 'Advanced',
    tagline: 'Pharmaceutical-grade blood bank refrigerator with continuous monitoring',
    keyFeatures: ['Pharmaceutical-grade blood bank storage', '1–6 °C precise temperature control', 'Continuous temperature monitoring', 'Door open and power failure alarms'],
    keySpecs: { 'Temp Range': '1–6 °C', 'Capacity': '300–800 L', 'Standards': 'AABB / CE marked' },
  },
  {
    name: 'Liquid Nitrogen Dewar (50L)',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Cold Chain & Storage', tier: 'Standard',
    tagline: '50 L liquid nitrogen dewar for cryogenic sample storage',
    keyFeatures: ['−196 °C cryogenic storage', 'Vented neck plug design', 'Low evaporation rate', 'Caster-equipped for mobility'],
    keySpecs: { 'Capacity': '50 L', 'Static Evaporation': '<0.3 L/day', 'Material': 'Aluminium vacuum vessel' },
  },
  {
    name: 'Bench-Top Autoclave (23L)',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Sterilization & Safety', tier: 'Standard',
    tagline: '23 L bench-top autoclave for rapid laboratory sterilisation',
    keyFeatures: ['Gravity and vacuum cycle options', '134 °C sterilisation', 'Pre-vacuum (B-class) cycles', 'Printer for cycle documentation'],
    keySpecs: { 'Chamber Volume': '23 L', 'Temperature': 'Up to 134 °C', 'Cycles': 'Gravity, vacuum, liquid' },
  },
  {
    name: 'Chemical Fume Hood (1.2m)',
    categoryId: 'lab-equipment', categoryTitle: 'Lab Equipment', familyName: 'Sterilization & Safety', tier: 'Advanced',
    tagline: '1.2 m ducted chemical fume hood with variable air volume control',
    keyFeatures: ['Variable air volume (VAV) control', 'Face velocity alarms', 'EN 14175 certified', 'Low-noise aerodynamic design'],
    keySpecs: { 'Width': '1200 mm', 'Standard': 'EN 14175 / ASHRAE 110', 'Face Velocity': '0.5 m/s average' },
  },

  // ── Centrifuges (product-page models) ─────────────────────────────────────
  {
    name: 'Sorvall Legend Micro 21R',
    categoryId: 'centrifuges', categoryTitle: 'Centrifuges', familyName: 'Microcentrifuges', tier: 'Premium',
    tagline: 'Refrigerated microcentrifuge up to 21,000 × g',
    keyFeatures: ['Refrigerated (−10 to +40 °C)', 'Quick-spin button', 'Bio-certified rotor lid option', '26 cm wide footprint'],
    keySpecs: { 'Max Speed': '21,300 × g', 'Capacity': '24 × 1.5/2.0 mL', 'Temperature': '−10 to +40 °C' },
  },
  {
    name: 'Pico 17 Microcentrifuge',
    categoryId: 'centrifuges', categoryTitle: 'Centrifuges', familyName: 'Microcentrifuges', tier: 'Standard',
    tagline: 'Ultra-compact personal microcentrifuge',
    keyFeatures: ['Ultra-compact personal centrifuge', 'Quiet motor', 'One-button quick spin', 'Low-cost lab standard'],
    keySpecs: { 'Max Speed': '17,000 × g', 'Capacity': '24 × 1.5/2.0 mL', 'Temperature': 'Ambient', 'Weight': '<5 kg' },
  },
  {
    name: 'Multifuge X Pro Series',
    categoryId: 'centrifuges', categoryTitle: 'Centrifuges', familyName: 'Benchtop & Floor-Standing Centrifuges', tier: 'Premium',
    tagline: 'High-capacity multi-rotor centrifuge for high-volume labs',
    keyFeatures: ['Auto-Lock rotor exchange', 'Bio-containment rotors', 'Blood bank protocols', 'LIMS connectivity'],
    keySpecs: { 'Max Speed': '25,830 × g', 'Capacity': '4 × 750 mL', 'Temperature': '−10 to +40 °C', 'Rotors': '>30 options' },
  },
  {
    name: 'Sorvall Legend XTR',
    categoryId: 'centrifuges', categoryTitle: 'Centrifuges', familyName: 'Benchtop & Floor-Standing Centrifuges', tier: 'Standard',
    tagline: 'Compact benchtop centrifuge with wide rotor compatibility',
    keyFeatures: ['Compact benchtop design', 'Wide rotor compatibility', 'Pre-programmed protocols', 'Quiet operation'],
    keySpecs: { 'Max Speed': '15,200 × g', 'Capacity': '4 × 400 mL', 'Temperature': '−10 to +40 °C' },
  },

  // ── Lab Consumables (application-page products) ───────────────────────────
  {
    name: 'Filtered Pipette Tips (10μL–1000μL)',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Pipette Tips & Tubes', tier: 'Standard',
    tagline: 'RNase/DNase-free filtered pipette tips (10 µL – 1000 µL)',
    keyFeatures: ['Aerosol barrier filter', 'RNase/DNase and pyrogen-free', 'Low-retention surface', 'Universal tip compatibility'],
    keySpecs: { 'Sizes': '10, 20, 100, 200, 1000 µL', 'Filter': 'Polyethylene aerosol barrier', 'Pack': '96/rack, 10 racks/box' },
  },
  {
    name: 'Low-Binding Microcentrifuge Tubes',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Pipette Tips & Tubes', tier: 'Standard',
    tagline: 'Low-binding microcentrifuge tubes for protein and nucleic acid work',
    keyFeatures: ['Low-retention surface treatment', 'RNase/DNase-free certified', '1.5 mL and 2.0 mL formats', 'Autoclavable'],
    keySpecs: { 'Volumes': '1.5 mL, 2.0 mL', 'Certifications': 'RNase, DNase, pyrogen-free', 'Temperature': '−80 to +121 °C' },
  },
  {
    name: 'PCR 8-Strip Tubes with Caps',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Pipette Tips & Tubes', tier: 'Standard',
    tagline: '0.2 mL PCR 8-strip tubes with flat and domed cap options',
    keyFeatures: ['Ultra-thin wall for fast heat transfer', 'Flat and domed cap options', 'Universal thermal cycler fit', 'RNase/DNase-free'],
    keySpecs: { 'Volume': '0.2 mL per tube', 'Format': '8-strip (×12 strips/frame)', 'Certifications': 'RNase/DNase-free' },
  },
  {
    name: '96-Well PCR Plate (semi-skirted)',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Microplates & Dishes', tier: 'Standard',
    tagline: 'Semi-skirted 96-well PCR plate for qPCR and endpoint PCR',
    keyFeatures: ['Semi-skirted for robot and manual use', 'Universal thermal cycler fit', 'Clear wells for optical detection', 'RNase/DNase-free certified'],
    keySpecs: { 'Wells': '96', 'Volume': '0.1 mL or 0.2 mL', 'Skirt': 'Semi-skirted SBS footprint' },
  },
  {
    name: '384-Well White Microplate',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Microplates & Dishes', tier: 'Advanced',
    tagline: '384-well white microplate for luminescent and fluorescent assays',
    keyFeatures: ['White walls for maximum signal reflection', 'Low crosstalk between wells', 'Automation-compatible SBS footprint', 'Low-binding surface option'],
    keySpecs: { 'Wells': '384', 'Well Volume': '30–120 µL', 'Surface': 'White polystyrene' },
  },
  {
    name: '6-Well Cell Culture Plate',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'Microplates & Dishes', tier: 'Standard',
    tagline: 'TC-treated 6-well cell culture plate for primary cell culture',
    keyFeatures: ['TC-treated for cell adhesion', 'Low evaporation lid', 'Gamma-irradiated sterile', 'Individual well colour-coded at base'],
    keySpecs: { 'Wells': '6', 'Well Volume': '16.8 mL max', 'Treatment': 'TC-treated' },
  },
  {
    name: 'Powder-Free Nitrile Gloves (M)',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'PPE & Lab Wear', tier: 'Standard',
    tagline: 'Powder-free nitrile examination gloves — size Medium',
    keyFeatures: ['Powder-free nitrile formulation', 'ASTM D6319 medical grade', 'EN374 chemical resistance rated', 'Textured fingertips'],
    keySpecs: { 'Material': 'Nitrile', 'Size': 'Medium (also XS, S, L, XL)', 'Pack': '100 gloves/box' },
  },
  {
    name: 'Chemical-Resistant Lab Coat',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'PPE & Lab Wear', tier: 'Standard',
    tagline: 'Chemical-resistant lab coat with snap fastening',
    keyFeatures: ['Chemical-resistant fabric', 'Snap or press-stud fastening', 'Knit cuffs for contamination control', 'Multiple size range'],
    keySpecs: { 'Material': 'Chemical-resistant polypropylene or cotton-poly', 'Sizes': 'S to XXXL', 'Standard': 'EN 13034 splash protection' },
  },
  {
    name: 'Anti-Fog Safety Goggles',
    categoryId: 'lab-consumables', categoryTitle: 'Lab Consumables', familyName: 'PPE & Lab Wear', tier: 'Standard',
    tagline: 'Impact-resistant anti-fog chemical splash safety goggles',
    keyFeatures: ['Anti-fog coating', 'Chemical splash rated', 'Indirect ventilation design', 'Fits over prescription glasses'],
    keySpecs: { 'Standard': 'EN166 / ANSI Z87.1', 'Ventilation': 'Indirect', 'Lens': 'Polycarbonate, UV-protective' },
  },

  // ── Plasticware (product-page models) ─────────────────────────────────────
  {
    name: 'Nalgene Bottles & Carboys',
    categoryId: 'plasticware', categoryTitle: 'Plasticware & Lab Supplies', familyName: 'Nalgene Labware', tier: 'Standard',
    tagline: 'Leak-proof chemical storage from 15 mL to 50 L',
    keyFeatures: ['HDPE, PP, PC, PETG materials', 'Wide-mouth and narrow-mouth', 'Autoclavable (PP, PC)', 'Spigot options for carboys'],
    keySpecs: { 'Materials': 'HDPE, PP, PC, PETG', 'Volumes': '15 mL – 50 L', 'Certifications': 'Non-pyrogenic, lot-traceable' },
  },
  {
    name: 'ART Filtered Pipette Tips',
    categoryId: 'plasticware', categoryTitle: 'Plasticware & Lab Supplies', familyName: 'Pipette Tips, Tubes & Plates', tier: 'Standard',
    tagline: 'ART aerosol-barrier filtered pipette tips for molecular workflows',
    keyFeatures: ['Aerosol barrier filter', 'Wide-bore and extended options', 'Colour-coded by volume', 'Low-retention surface'],
    keySpecs: { 'Sizes': '10, 20, 100, 200, 1000 µL', 'Filter': 'Polyethylene aerosol barrier', 'Certifications': 'RNase, DNase, pyrogen-free' },
  },
  {
    name: 'Nunc Cell Culture Plates',
    categoryId: 'plasticware', categoryTitle: 'Plasticware & Lab Supplies', familyName: 'Pipette Tips, Tubes & Plates', tier: 'Advanced',
    tagline: 'Nunc TC-treated and MaxiSorp cell culture microplates',
    keyFeatures: ['TC-treated for cell adhesion', 'MaxiSorp for ELISA', 'Ultra-low attachment spheroid format', 'Clear bottom for imaging'],
    keySpecs: { 'Formats': '6, 12, 24, 48, 96-well', 'Surface': 'TC-treated, MaxiSorp, ULA', 'Sterility': 'Gamma-irradiated' },
  },

  // ── Liquid Handling & Lab Automation (application-page products) ──────────
  {
    name: 'Electronic Single-Channel Pipette',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Electronic Pipettes', tier: 'Advanced',
    tagline: 'Bluetooth-enabled electronic single-channel pipette',
    keyFeatures: ['CV < 0.5% at nominal volume', 'Bluetooth data logging', 'Programmable mixing/dispensing', 'GLP-compliant calibration records'],
    keySpecs: { 'Volume Range': '0.1 µL – 10 mL', 'Mode': 'Pipetting, dispensing, dilution, mixing' },
  },
  {
    name: 'Electronic 12-Channel Pipette',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Electronic Pipettes', tier: 'Advanced',
    tagline: 'Electronic 12-channel multichannel pipette for plate-based workflows',
    keyFeatures: ['12-channel simultaneous dispensing', 'Consistent low-CV across channels', 'Reverse pipetting mode', 'Adjustable tip spacing'],
    keySpecs: { 'Channels': '12', 'Volume Range': '5–300 µL per channel', 'CV': '<1% at nominal volume' },
  },
  {
    name: 'Pipette Calibration System',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Electronic Pipettes', tier: 'Standard',
    tagline: 'Balance-based gravimetric pipette calibration and verification system',
    keyFeatures: ['ISO 8655-compliant calibration', 'Automated gravimetric protocol', 'GLP report generation', 'Traceable to NIST standards'],
    keySpecs: { 'Method': 'Gravimetric (ISO 8655)', 'Accuracy': '±0.001 mg balance', 'Output': 'PDF / CSV calibration report' },
  },
  {
    name: '96-Channel Liquid Handling Robot',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Robotic Liquid Handlers', tier: 'Premium',
    tagline: '96-channel pipetting robot for NGS prep, ELISA, and drug discovery',
    keyFeatures: ['96 simultaneous channels', 'Sub-µL accuracy and precision', 'Integrated labware gripper', 'Method programming software'],
    keySpecs: { 'Channels': '96 (or 384)', 'Volume Range': '0.5–200 µL', 'Accuracy': '<1 µL at low volumes' },
  },
  {
    name: 'Compact 8-Channel Workstation',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Robotic Liquid Handlers', tier: 'Advanced',
    tagline: 'Compact 8-channel automated liquid handling workstation',
    keyFeatures: ['8-channel independent aspiration', 'Compact benchtop footprint', 'Deck-configurable labware positions', 'Pre-built application protocols'],
    keySpecs: { 'Channels': '8 independent', 'Volume Range': '1–1000 µL', 'Deck Positions': '6–12' },
  },
  {
    name: 'Automated Plate Sealer',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Robotic Liquid Handlers', tier: 'Standard',
    tagline: 'Automated heat or pressure sealer for microplates',
    keyFeatures: ['Heat or pressure sealing', '96, 384, 1536-well plate compatible', 'SBS footprint integration', 'Seal verification output'],
    keySpecs: { 'Seal Types': 'Adhesive, heat, pressure', 'Compatibility': '96, 384, 1536-well SBS plates', 'Cycle Time': '<10 seconds/plate' },
  },
  {
    name: 'Microplate Washer (96/384-well)',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Automated Dispensers & Washers', tier: 'Advanced',
    tagline: 'High-throughput microplate washer for 96 and 384-well ELISA plates',
    keyFeatures: ['96/384-well compatible manifolds', 'Vacuum and positive-pressure wash', 'Protocol storage and recall', 'Soak timer function'],
    keySpecs: { 'Plate Formats': '96, 384-well', 'Aspiration': 'Dual-row manifold', 'Priming Volume': '<3 mL' },
  },
  {
    name: 'Automated Reagent Dispenser',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Automated Dispensers & Washers', tier: 'Advanced',
    tagline: 'Programmable microplate reagent dispenser with peristaltic pump',
    keyFeatures: ['Adjustable volume 1–2000 µL', 'Peristaltic or syringe pump', '8 or 16 channel cassette', 'Protocol storage and recall'],
    keySpecs: { 'Volume Range': '1–2000 µL/well', 'Channels': '8 or 16', 'Speed': '<20 seconds per 96-well plate' },
  },
  {
    name: 'Automated Plate Stacker',
    categoryId: 'liquid-handling-automation', categoryTitle: 'Liquid Handling & Lab Automation', familyName: 'Automated Dispensers & Washers', tier: 'Advanced',
    tagline: 'Robotic plate stacker for unattended high-throughput plate processing',
    keyFeatures: ['Holds 50+ plates per stack', 'Barcode reader integration', 'Compatible with SBS labware', 'Open API for system integration'],
    keySpecs: { 'Capacity': '50+ plates per tower', 'Format': 'SBS microplates (96, 384-well)', 'Transfer Speed': '<3 seconds/plate' },
  },

  // ── LIMS & Software (application-page products) ───────────────────────────
  {
    name: 'Cloud LIMS (SaaS)',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Laboratory Information Management (LIMS)', tier: 'Advanced',
    tagline: 'Cloud-hosted SaaS LIMS for sample tracking and results reporting',
    keyFeatures: ['Full sample chain-of-custody', '21 CFR Part 11 audit trail', 'Instrument bidirectional interfacing', 'Custom CoA and report generation'],
    keySpecs: { 'Deployment': 'Cloud (SaaS)', 'Compliance': '21 CFR Part 11, GAMP 5', 'Access': 'Browser-based, mobile-ready' },
  },
  {
    name: 'On-Premise Enterprise LIMS',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Laboratory Information Management (LIMS)', tier: 'Premium',
    tagline: 'On-premise enterprise LIMS for regulated and high-volume labs',
    keyFeatures: ['On-premise data sovereignty', 'Enterprise-scale multi-site', 'ERP and LIMS integration', 'Role-based user permissions'],
    keySpecs: { 'Deployment': 'On-premise server', 'Users': 'Unlimited (enterprise licence)', 'Integration': 'HL7, SAP, Oracle ERP' },
  },
  {
    name: 'LIMS Implementation Service',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Laboratory Information Management (LIMS)', tier: 'Standard',
    tagline: 'End-to-end LIMS implementation, validation, and training service',
    keyFeatures: ['Needs assessment and gap analysis', 'Configuration and customisation', 'IQ/OQ/PQ validation support', 'Staff training and go-live support'],
    keySpecs: { 'Scope': 'LIMS configuration, validation, training', 'Timeline': '4–16 weeks typical' },
  },
  {
    name: 'Electronic Lab Notebook (ELN)',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Instrument Data Management', tier: 'Advanced',
    tagline: 'Cloud or on-premise electronic lab notebook for research data capture',
    keyFeatures: ['Structured experiment templates', 'Instrument data import', 'e-Signature and audit trail', 'IP protection and version control'],
    keySpecs: { 'Compliance': '21 CFR Part 11, EU Annex 11', 'Deployment': 'Cloud or on-premise' },
  },
  {
    name: 'Scientific Data Management Platform',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Instrument Data Management', tier: 'Premium',
    tagline: 'Unified scientific data management for multi-instrument labs',
    keyFeatures: ['Multi-vendor instrument integration', 'Cloud backup and disaster recovery', 'Automated data review rules', 'AI-assisted trend analysis'],
    keySpecs: { 'Instruments Supported': 'LC, GC, MS, qPCR, spectroscopy', 'Storage': 'Cloud / on-premise hybrid' },
  },
  {
    name: 'Quality Management System (QMS)',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Quality & Compliance Tools', tier: 'Advanced',
    tagline: 'ISO 17025 / GMP quality management system software',
    keyFeatures: ['Document and SOP control', 'CAPA and deviation tracking', 'Audit management module', 'ISO 17025 and GMP gap analysis'],
    keySpecs: { 'Standards': 'ISO 17025, ISO 15189, GMP, GLP', 'Deployment': 'Cloud or on-premise' },
  },
  {
    name: 'Calibration Management Software',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Quality & Compliance Tools', tier: 'Standard',
    tagline: 'Equipment calibration scheduling and certificate management software',
    keyFeatures: ['Equipment calibration scheduler', 'Automated reminder notifications', 'Certificate storage and retrieval', 'Out-of-tolerance workflow'],
    keySpecs: { 'Assets': 'Unlimited instruments/assets', 'Compliance': 'ISO 17025, GMP equipment qualification' },
  },
  {
    name: 'Audit Preparation Toolkit',
    categoryId: 'lims-software', categoryTitle: 'LIMS & Software', familyName: 'Quality & Compliance Tools', tier: 'Standard',
    tagline: 'Pre-audit preparation toolkit for ISO, GMP, and NABL inspections',
    keyFeatures: ['Pre-audit checklist templates', 'Gap assessment questionnaires', 'Mock audit scheduling', 'Corrective action tracker'],
    keySpecs: { 'Standards Covered': 'ISO 17025, ISO 15189, GMP, NABL' },
  },

  // ── Refrigerators (product-page models) ──────────────────────────────────
  {
    name: 'TSX Series 51 cu. ft. Refrigerator',
    categoryId: 'refrigerators', categoryTitle: 'Refrigerators & Cold Storage', familyName: 'TSX Series High-Performance Refrigerators', tier: 'Premium',
    tagline: 'V-drive adaptive cooling — ±0.5 °C uniformity',
    keyFeatures: ['V-drive adaptive compressor', '±0.5 °C uniformity', 'USB temperature data export', 'Up to 30% energy savings'],
    keySpecs: { 'Capacity': '51.1 cu. ft. (1447 L)', 'Temp Range': '1–8 °C', 'Uniformity': '±0.5 °C' },
  },
  {
    name: 'TSE Series 564 L Refrigerator',
    categoryId: 'refrigerators', categoryTitle: 'Refrigerators & Cold Storage', familyName: 'TSE & TSG Series Refrigerators', tier: 'Standard',
    tagline: 'Economical single-door lab refrigerator',
    keyFeatures: ['Economical lab storage', 'Compact single-door design', 'Easy-clean interior', 'Audible high/low alarm'],
    keySpecs: { 'Capacity': '564 L', 'Temp Range': '1–10 °C', 'Shelves': '3 adjustable' },
  },
  {
    name: 'TSG Series 1297 L Refrigerator',
    categoryId: 'refrigerators', categoryTitle: 'Refrigerators & Cold Storage', familyName: 'TSE & TSG Series Refrigerators', tier: 'Advanced',
    tagline: 'High-capacity double-door lab refrigerator',
    keyFeatures: ['High-capacity double-door', 'Uniform forced-air circulation', 'Door-open alarm', 'Sample prep area storage'],
    keySpecs: { 'Capacity': '1297 L', 'Temp Range': '1–10 °C', 'Shelves': '6 adjustable', 'Alarm': 'Audible + visual' },
  },

  // ── Turnkey Lab Design (application-page products) ────────────────────────
  {
    name: 'Lab Design Consultation Package',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Laboratory Planning & Design', tier: 'Standard',
    tagline: 'Comprehensive lab design consultation and needs assessment',
    keyFeatures: ['CAD and BIM 3D design', 'Workflow and space optimisation', 'Regulatory compliance review', 'Utilities and HVAC planning'],
    keySpecs: { 'Deliverables': 'CAD floor plan, BIM model, compliance report', 'Scope': 'Greenfield or refurbishment' },
  },
  {
    name: '3D BIM Lab Model',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Laboratory Planning & Design', tier: 'Advanced',
    tagline: 'Full BIM 3D model of planned laboratory for pre-build review',
    keyFeatures: ['Revit/Archicad BIM format', 'Equipment layout and utilities', 'Clash detection review', 'Virtual walkthrough export'],
    keySpecs: { 'Format': 'Revit / IFC BIM model', 'Includes': 'MEP, furniture, equipment layout' },
  },
  {
    name: 'Regulatory Compliance Report',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Laboratory Planning & Design', tier: 'Standard',
    tagline: 'Laboratory regulatory compliance gap report for ISO/GMP labs',
    keyFeatures: ['ISO 17025 / GMP gap analysis', 'NABL readiness assessment', 'Corrective action priority list', 'Expert reviewer sign-off'],
    keySpecs: { 'Standards': 'ISO 17025, ISO 15189, GMP, NABL', 'Format': 'Formal written report with findings' },
  },
  {
    name: 'Height-Adjustable Lab Bench',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Modular Lab Furniture', tier: 'Advanced',
    tagline: 'Ergonomic height-adjustable laboratory bench (680–1000 mm)',
    keyFeatures: ['Adjustable 680–1000 mm height', 'Chemical-resistant epoxy resin tops', 'Modular and reconfigurable', 'Load-rated to 150 kg/linear meter'],
    keySpecs: { 'Height Range': '680–1000 mm', 'Worktop': 'Epoxy resin chemical-resistant', 'Load': '150 kg/linear metre' },
  },
  {
    name: 'Overhead Storage Cabinet',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Modular Lab Furniture', tier: 'Standard',
    tagline: 'Modular overhead storage cabinet for laboratory wall mounting',
    keyFeatures: ['Powder-coated steel construction', 'Adjustable internal shelves', 'Lockable door option', 'Standard depth 300 mm'],
    keySpecs: { 'Widths': '600, 900, 1200 mm', 'Depth': '300 mm', 'Material': 'Powder-coated steel' },
  },
  {
    name: 'Mobile Trolley Unit',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Modular Lab Furniture', tier: 'Standard',
    tagline: 'Wheeled mobile laboratory trolley for flexible workspace use',
    keyFeatures: ['Lockable castors', 'Chemical-resistant worktop', 'Drawer and shelf options', 'Pushbar handle'],
    keySpecs: { 'Dimensions': '600 × 450 × 900 mm (typical)', 'Castors': '100 mm lockable', 'Worktop': 'Epoxy resin or HPL' },
  },
  {
    name: '1.2m Ducted Fume Cupboard',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Fume Hoods & Containment', tier: 'Advanced',
    tagline: '1.2 m ducted fume cupboard EN 14175 certified',
    keyFeatures: ['Variable air volume (VAV) control', 'Airflow monitoring and alarms', 'EN 14175 / ASHRAE 110 certified', 'Low-noise aerodynamic baffles'],
    keySpecs: { 'Width': '1200 mm', 'Standard': 'EN 14175', 'Face Velocity': '0.5 m/s average' },
  },
  {
    name: 'Ductless Filtered Fume Hood',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Fume Hoods & Containment', tier: 'Advanced',
    tagline: 'Ductless carbon-filtered fume hood — no ducting required',
    keyFeatures: ['Activated carbon filter array', 'No duct installation required', 'Filter saturation monitor', 'Recirculates HEPA-cleaned air'],
    keySpecs: { 'Filtration': 'Activated carbon + HEPA', 'Standard': 'EN 14175 Type NU', 'Filter Life': '6–12 months typical' },
  },
  {
    name: 'Laminar Flow Clean Bench',
    categoryId: 'turnkey-lab-design', categoryTitle: 'Turnkey Lab Design & Furniture', familyName: 'Fume Hoods & Containment', tier: 'Standard',
    tagline: 'Horizontal or vertical laminar flow clean bench for sample protection',
    keyFeatures: ['HEPA filtered laminar airflow', 'UV lamp for surface decontamination', 'ISO Class 5 (Class 100) work area', 'Low-noise fan unit'],
    keySpecs: { 'Cleanliness': 'ISO Class 5 (0.5 µm particles)', 'Airflow': 'Vertical or horizontal HEPA', 'HEPA Efficiency': '99.99% at 0.3 µm' },
  },

  // ── Turnkey Lab Setup (product-page models) ───────────────────────────────
  {
    name: 'Molecular Biology Lab Setup',
    categoryId: 'turnkey-lab-setup', categoryTitle: 'Turnkey Lab Setup', familyName: 'Lab Design & Build Services', tier: 'Premium',
    tagline: 'Complete turnkey molecular biology laboratory — PCR to NGS',
    keyFeatures: ['PCR suite with positive/negative areas', 'Dedicated extraction room', 'ISO Class 5–7 clean room options', 'IQ/OQ/PQ documentation'],
    keySpecs: { 'Scope': 'PCR, qPCR, NGS, extraction', 'Clean Room': 'ISO Class 5–7', 'Validation': 'IQ/OQ/PQ documentation' },
  },
  {
    name: 'Clinical & Diagnostics Lab Setup',
    categoryId: 'turnkey-lab-setup', categoryTitle: 'Turnkey Lab Setup', familyName: 'Lab Design & Build Services', tier: 'Advanced',
    tagline: 'NABL/ISO 15189-ready clinical diagnostics laboratory turnkey setup',
    keyFeatures: ['NABL accreditation support', 'BSL-2 safety design', 'Automated sample transport option', 'Patient flow optimisation'],
    keySpecs: { 'Scope': 'Biochemistry, haematology, serology', 'Standards': 'NABL / ISO 15189', 'Safety': 'BSL-2 containment' },
  },

  // ── Truenat (product-page models) ────────────────────────────────────────
  {
    name: 'Truelab Uno Dx Analyser',
    categoryId: 'mol-bio', categoryTitle: 'Molecular Biology — Truenat', familyName: 'Truenat Real-Time PCR Platform', tier: 'Standard',
    tagline: 'Single-test portable Truenat analyser — battery-powered field use',
    keyFeatures: ['Chip-based real-time qPCR', 'Battery-powered portable', 'Cloud data upload', 'WHO-endorsed for TB testing'],
    keySpecs: { 'Technology': 'Chip-based real-time qPCR', 'Channels': '2 fluorescence', 'Power': 'Battery or mains', 'Weight': '<1 kg' },
  },
  {
    name: 'Truelab Quattro Analyser',
    categoryId: 'mol-bio', categoryTitle: 'Molecular Biology — Truenat', familyName: 'Truenat Real-Time PCR Platform', tier: 'Advanced',
    tagline: '4-sample concurrent Truenat analyser for higher throughput',
    keyFeatures: ['4-sample concurrent testing', 'Wi-Fi and Bluetooth connectivity', 'Multi-disease screening', 'Integrated data management'],
    keySpecs: { 'Technology': 'Chip-based real-time qPCR', 'Channels': '4 fluorescence', 'Throughput': '4 samples simultaneously' },
  },

  // ── Orbitrap Mass Spectrometry (product-page models) ─────────────────────
  {
    name: 'Orbitrap Astral Zoom',
    categoryId: 'lab-solutions', categoryTitle: 'Lab Solutions & Mass Spectrometry', familyName: 'Orbitrap Mass Spectrometry', tier: 'Premium',
    tagline: 'Ultra-high resolution Orbitrap — 500,000 FWHM, 200 Hz MS/MS',
    keyFeatures: ['Deep proteome coverage', 'Astral analyser for speed', 'DIA and DDA acquisition', 'Clinical research applications'],
    keySpecs: { 'Resolution': 'Up to 500,000 FWHM', 'Mass Accuracy': '<1 ppm', 'Scan Speed': '200 Hz MS/MS' },
  },
  {
    name: 'Orbitrap Excedion Series',
    categoryId: 'lab-solutions', categoryTitle: 'Lab Solutions & Mass Spectrometry', familyName: 'Orbitrap Mass Spectrometry', tier: 'Advanced',
    tagline: 'Biopharmaceutical characterisation with 240,000 FWHM Orbitrap',
    keyFeatures: ['Biopharmaceutical characterisation', 'Intact and native MS', 'Small molecule quantitation', 'Multi-attribute method (MAM)'],
    keySpecs: { 'Resolution': 'Up to 240,000 FWHM', 'Mass Accuracy': '<1 ppm RMS', 'Mass Range': '50–8000 m/z' },
  },

  // ── Backup Lab & Training (product-page models) ───────────────────────────
  {
    name: 'Genomics Training Programme',
    categoryId: 'backup-lab-training', categoryTitle: 'Backup Lab & Training Centre', familyName: 'Decipher Genomics & Research Centre', tier: 'Standard',
    tagline: 'Hands-on genomics training programme — 1 to 5-day modules',
    keyFeatures: ['Customisable training modules', 'Certificate of completion', 'Post-training support', 'Application-specific workflows'],
    keySpecs: { 'Topics': 'PCR, qPCR, NGS, Sanger, extraction', 'Duration': '1–5 day modules', 'Max Batch': '10 participants' },
  },
  {
    name: 'Backup Laboratory Services',
    categoryId: 'backup-lab-training', categoryTitle: 'Backup Lab & Training Centre', familyName: 'Decipher Genomics & Research Centre', tier: 'Standard',
    tagline: 'Instrument access and expert support during equipment downtime',
    keyFeatures: ['Instrument access during downtime', 'Expert application support', 'Confidential sample handling', 'Same-day turnaround service'],
    keySpecs: { 'Equipment': 'PCR, qPCR, sequencer, centrifuge', 'Availability': 'By appointment', 'Turnaround': 'Same-day results' },
  },

  // ── Service Management (application-page products) ────────────────────────
  {
    name: 'IQ/OQ Validation Service',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Installation & Qualification (IQ/OQ/PQ)', tier: 'Advanced',
    tagline: 'IQ and OQ validation service for GMP and ISO instrument compliance',
    keyFeatures: ['IQ and OQ protocol execution', 'Electronic validation documentation', 'FDA/EU GMP compliant reports', 'Deviation report and CAPA support'],
    keySpecs: { 'Scope': 'Installation Qualification + Operational Qualification', 'Compliance': 'FDA / EU GMP, ISO 17025' },
  },
  {
    name: 'PQ Performance Qualification',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Installation & Qualification (IQ/OQ/PQ)', tier: 'Advanced',
    tagline: 'Performance qualification service to confirm instrument fitness for purpose',
    keyFeatures: ['Application-specific PQ testing', 'System suitability test (SST)', 'Full electronic documentation', 'Requalification scheduling'],
    keySpecs: { 'Scope': 'Performance Qualification in user environment', 'Output': 'Signed PQ report with all test data' },
  },
  {
    name: 'Validation Documentation Package',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Installation & Qualification (IQ/OQ/PQ)', tier: 'Standard',
    tagline: 'Template IQ/OQ/PQ validation documentation package',
    keyFeatures: ['Pre-written IQ/OQ/PQ protocols', 'Risk assessment templates', 'Deviation and CAPA forms', 'Instrument-specific content'],
    keySpecs: { 'Format': 'Word / PDF editable templates', 'Standards': '21 CFR Part 11, EU Annex 11, GAMP 5' },
  },
  {
    name: 'Pipette Calibration Service',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Calibration & NABL Testing', tier: 'Standard',
    tagline: 'NABL-accredited pipette calibration service with traceable certificate',
    keyFeatures: ['NABL-accredited calibration', 'ISO 8655 gravimetric method', 'Traceable certificate issued', 'On-site or in-lab options'],
    keySpecs: { 'Method': 'ISO 8655 gravimetric', 'Accreditation': 'NABL / ISO/IEC 17025', 'Report': 'Traceable calibration certificate' },
  },
  {
    name: 'Balance Calibration Certificate',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Calibration & NABL Testing', tier: 'Standard',
    tagline: 'Traceable balance calibration and certificate issuance service',
    keyFeatures: ['OIML / NABL traceable weights', 'Repeatability and linearity testing', 'GLP-format certificate', 'On-site available'],
    keySpecs: { 'Method': 'OIML / ISO/IEC 17025', 'Weights Used': 'Class E2/F1 traceable weights' },
  },
  {
    name: 'Temperature Logger Verification',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Calibration & NABL Testing', tier: 'Standard',
    tagline: 'Traceable temperature logger and thermometer verification service',
    keyFeatures: ['Temperature device verification', 'Traceable to NIST/NPL', 'Certificate of calibration', 'Refrigerator, freezer, incubator probes'],
    keySpecs: { 'Devices': 'Data loggers, thermometers, RTDs, thermocouples', 'Range': '−80 °C to +300 °C' },
  },
  {
    name: 'Comprehensive AMC Package',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Annual Maintenance Contracts (AMC)', tier: 'Premium',
    tagline: 'All-inclusive annual maintenance contract with OEM parts',
    keyFeatures: ['Scheduled preventive maintenance', 'Priority emergency response (4–24 hr)', 'Genuine OEM parts included', 'Application and method support'],
    keySpecs: { 'Coverage': 'Preventive + corrective maintenance', 'Response': '4–24 hours emergency', 'Parts': 'Genuine OEM included' },
  },
  {
    name: 'Preventive Maintenance Service',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Annual Maintenance Contracts (AMC)', tier: 'Standard',
    tagline: 'Scheduled preventive maintenance visit and performance verification',
    keyFeatures: ['Annual or bi-annual PM visit', 'Performance parameter testing', 'Lubrication and parts check', 'PM report issued'],
    keySpecs: { 'Frequency': 'Annual or bi-annual', 'Output': 'PM service report', 'Duration': 'Half-day to full-day per instrument' },
  },
  {
    name: 'Emergency Repair Contract',
    categoryId: 'service-management', categoryTitle: 'Service Management', familyName: 'Annual Maintenance Contracts (AMC)', tier: 'Standard',
    tagline: 'Priority emergency repair contract for rapid instrument recovery',
    keyFeatures: ['Priority response SLA (4–8 hours)', 'Qualified field service engineers', 'Parts availability guarantee', 'Root-cause failure report'],
    keySpecs: { 'Response Time': '4–8 hours (business hours)', 'Coverage': 'Labour + travel; parts extra or bundled' },
  },
];

module.exports = { catalog };
